name: Build EXE from Python Script

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install FFmpeg
      run: choco install ffmpeg

    - name: Run pyinstaller to build EXE
      run: |
        pyinstaller --onefile --distpath dist --workpath build --specpath . mp3.py

- name: Upload EXE as Artifact
  uses: actions/upload-artifact@v2
  with:
    name: mp3-exe
    path: dist/mp3.exe
